# Change these first
owner: Logic Brains Technologies # Your GitHub organization or username, where this repository lives
repo: logicbrains-upptime # The name of this repository

sites:
  - name: Aprende con Confianza
    url: https://aprendeconconfianza.cl

asignados : # Usuarios para asignar problemas de tiempo de inactividad (opcional) 
  -architecture-development _

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.logicbrains.cl
  # baseUrl: /your-repo-name
  name: Estados de nuestros servicios
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  introTitle: "**Monitor** de estados de nuestros servicios."
  introMessage: En nuestro repositorio de github podras indicar cualquier incidencia con nosotros ante cualquier eventualidad. 
  navbar:
    - title: Status
      href: /
    - title: Logic Brains
      href: "https://github.com/Logic-Brains-Technologies/logicbrains-upptime"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
