# Change these first
owner: Logic-Brains-Technologies # Your GitHub organization or username, where this repository lives
repo: logicbrains-upptime # The name of this repository

sites:
  - name: Aprende con Confianza
    url: https://www.aprendeconconfianza.cl

assignees: # Usuarios para asignar problemas de tiempo de inactividad (opcional) 
  - cchaconlbt
  - mpizarrolbt
  - architecture-development

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  themeUrl: https://raw.githubusercontent.com/Logic-Brains-Technologies/logicbrains-upptime/master/assets/style-logicbrains.css
  cname: status.logicbrains.cl
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/Logic-Brains-Technologies/logicbrains-upptime/master/assets/logo-logicbrains-white.svg
  name: Logic Brains Services Status
  introTitle: "**Monitor** de estados de nuestros servicios."
  introMessage: En nuestro repositorio de github podras indicar cualquier incidencia con nosotros ante cualquier eventualidad. 
  navbar:
    - title: Status
      href: /
    - title: Logic Brains GitHub
      href: https://github.com/Logic-Brains-Technologies/logicbrains-upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
